In [8]:
import numpy as np

### Load and Generate function

In [10]:
lending_co_data_numeric_1=np.loadtxt("Lending-Company-Numeric-Data.csv",delimiter=",")

In [12]:
lending_co_data_numeric_1

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [13]:
lending_co_data_numeric_2=np.genfromtxt("Lending-Company-Numeric-Data.csv",delimiter=",")

In [14]:
lending_co_data_numeric_2

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [15]:
np.array_equal(lending_co_data_numeric_1,lending_co_data_numeric_2)

True

In [18]:
lending_co_data_numeric_NAN=np.loadtxt("Lending-Company-Numeric-Data.csv",delimiter=';',dtype=np.str)
lending_co_data_numeric_NAN

<ipython-input-18-ad7f2fc10a72>:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  lending_co_data_numeric_NAN=np.loadtxt("Lending-Company-Numeric-Data.csv",delimiter=';',dtype=np.str)


array(['2000,40,365,3121,4241,13621', '2000,40,365,3061,4171,15041',
       '1000,40,365,2160,3280,15340', ..., '2000,40,365,4201,5001,16600',
       '1000,40,365,2080,3320,15600', '2000,40,365,4601,4601,16600'],
      dtype='<U30')

### Partial Cleaning While Importing

In [19]:
lending_co_data_numeric_NAN=np.loadtxt("Lending-Company-Numeric-Data-NAN.csv",delimiter=';',dtype=np.str)
lending_co_data_numeric_NAN

<ipython-input-19-634886732dfa>:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  lending_co_data_numeric_NAN=np.loadtxt("Lending-Company-Numeric-Data-NAN.csv",delimiter=';',dtype=np.str)


array([['2000', '40', '365', '3121', '4241', '13621'],
       ['2000', '40', '365', '3061', '4171', '15041'],
       ['1000', '40', '365', '2160', '3280', '15340'],
       ...,
       ['', '40', '365', '4201', '5001', '16600'],
       ['1000', '40', '365', '2080', '3320', '15600'],
       ['2000', '40', '365', '4601', '4601', '16600']], dtype='<U5')

In [21]:
lending_co_data_numeric_NAN=np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv",delimiter=';',skip_header=2)
lending_co_data_numeric_NAN

array([[ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [22]:
lending_co_data_numeric_NAN=np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv",delimiter=';',skip_footer=2)
lending_co_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  3401.,    nan, 16600.],
       [ 2000.,    40.,   365.,    nan,  5440., 16600.],
       [   nan,    40.,   365.,  4201.,  5001., 16600.]])

In [25]:
lending_co_data_numeric_NAN=np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv",
                                          delimiter=';',
                                          usecols=(0,2,5))
lending_co_data_numeric_NAN

array([[ 2000.,   365., 13621.],
       [ 2000.,   365., 15041.],
       [ 1000.,   365., 15340.],
       ...,
       [   nan,   365., 16600.],
       [ 1000.,   365., 15600.],
       [ 2000.,   365., 16600.]])

In [27]:
lending_co_data_numeric_NAN=np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv",
                                          delimiter=';',
                                          usecols=(0,2,5),
                                         skip_header=2,
                                         skip_footer=2)
lending_co_data_numeric_NAN

array([[ 1000.,   365., 15340.],
       [ 2000.,   365., 15321.],
       [ 2000.,   365., 13720.],
       ...,
       [ 2000.,   365., 16600.],
       [ 2000.,   365., 16600.],
       [   nan,   365., 16600.]])

In [30]:
lending_co_data_0,lending_co_data_2,lending_co_data_5=np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv",
                                          delimiter=';',
                                          usecols=(0,2,5),
                                         skip_header=2,
                                         skip_footer=2,
                                        unpack=True)
print(lending_co_data_0)
print(lending_co_data_2)
print(lending_co_data_5)

[1000. 2000. 2000. ... 2000. 2000.   nan]
[365. 365. 365. ... 365. 365. 365.]
[15340. 15321. 13720. ... 16600. 16600. 16600.]
