In [1]:
import numpy as np


## Create nd array


In [3]:
array_empty=np.empty(shape=(2,3))
array_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
array_zeros=np.zeros(shape=(2,3))
array_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
array_zeros=np.zeros(shape=(2,3),dtype=np.float32)
array_zeros

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [7]:
array_ones=np.ones(shape=(2,3))
array_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
array_full=np.full(shape=(2,3),fill_value=9)
array_full

array([[9, 9, 9],
       [9, 9, 9]])

## _like function

In [10]:
matrix_A=np.array([[1,0,2,3,5],[4,7,8,9,10],[7,6,4,5,3]])
matrix_A

array([[ 1,  0,  2,  3,  5],
       [ 4,  7,  8,  9, 10],
       [ 7,  6,  4,  5,  3]])

In [11]:
array_empty_like=np.empty_like(matrix_A)
array_empty_like

array([[ 1,  0,  2,  3,  5],
       [ 4,  7,  8,  9, 10],
       [ 7,  6,  4,  5,  3]])

In [12]:
array_zero_like=np.zeros_like(matrix_A)
array_zero_like

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## .arange function 

In [13]:
list(range(30))

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29]

In [14]:
array_rng=np.arange(30)
array_rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [15]:
array_rng=np.arange(start=30)
array_rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [16]:
array_rng=np.arange(start=0,stop=30)
array_rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [17]:
array_rng=np.arange(start=0,stop=30,step=2)
array_rng

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [18]:
array_rng=np.arange(start=0,stop=30,step=2,dtype=np.float64)
array_rng

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24.,
       26., 28.])

## Random Generators

### Defining

In [19]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [23]:
array_RG=gen(pcg())
array_RG.normal(size=(5,5))

array([[-0.41688785,  2.37071171, -0.39367589, -1.28962584, -0.78395244],
       [-0.36873321,  1.15023556,  1.0782981 ,  1.32744405,  1.57847536],
       [ 0.09453452, -0.35742518,  0.57291141, -0.65132911,  0.88133861],
       [-2.15534473, -1.19362833, -2.05860232, -0.73811873, -1.64400385],
       [-0.28570543, -0.05714289, -0.64681586,  0.61196907,  0.1472282 ]])

In [24]:
array_RG=gen(pcg(seed=365))
array_RG.normal(size=(5,5))

array([[-0.13640899,  0.09414431, -0.06300442,  1.05391641, -0.6866818 ],
       [-0.50922173, -0.7999526 ,  0.73041825,  0.08825439, -2.1177576 ],
       [ 0.65526774, -0.48095012, -0.5519114 , -0.58578662, -0.98257896],
       [ 1.12378166, -1.30984316, -0.04703774,  0.955272  ,  0.26071745],
       [-0.20023668, -1.50172484, -1.4929163 ,  0.96535084,  1.18694633]])

In [25]:
array_RG.normal(size=(5,5))

array([[-0.76065577,  1.48158358,  0.01200258, -0.06846959,  0.25301664],
       [-0.52640788,  0.79613109,  0.28203421,  1.80238008,  0.93932117],
       [-0.53693283, -0.26317689, -1.77723035,  1.14900013, -2.20733915],
       [ 1.54116775, -0.5124932 , -2.14564563,  1.98878673,  0.32208907],
       [-1.2651495 ,  3.2714633 ,  1.78650493, -0.20233675,  0.20427467]])

### Generating Integers, Probabilities and Random Choice

In [28]:
array_RG=gen(pcg(seed=365))
array_RG.integers(low=10,high=100,size=(5,5))

array([[18, 78, 64, 78, 84],
       [66, 67, 28, 10, 69],
       [45, 15, 37, 74, 96],
       [19, 21, 89, 73, 54],
       [53, 84, 66, 51, 92]], dtype=int64)

In [30]:
array_RG=gen(pcg(seed=365))
array_RG.random(size=(5,5))

array([[0.75915734, 0.7662218 , 0.6291028 , 0.20336599, 0.66501486],
       [0.06559111, 0.71326309, 0.10812106, 0.87969046, 0.49405844],
       [0.82472673, 0.45652944, 0.07367232, 0.69628564, 0.36690736],
       [0.29787156, 0.4996155 , 0.4865245 , 0.62740703, 0.54952637],
       [0.64894629, 0.04411757, 0.7206516 , 0.84594003, 0.17159792]])

In [32]:
array_RG=gen(pcg(seed=365))
array_RG.choice([1,2,3,4,5],size=(5,5))

array([[1, 4, 4, 4, 5],
       [4, 4, 2, 1, 4],
       [2, 1, 2, 4, 5],
       [1, 1, 5, 4, 3],
       [3, 5, 4, 3, 5]])

### Generating Arrays From Known Distributions

In [33]:
array_RG=gen(pcg(seed=365))
array_RG.poisson(size=(5,5))

array([[2, 0, 1, 1, 2],
       [1, 1, 0, 1, 1],
       [1, 2, 1, 1, 0],
       [0, 1, 0, 2, 1],
       [0, 1, 0, 0, 2]], dtype=int64)

In [34]:
array_RG=gen(pcg(seed=365))
array_RG.poisson(lam=10,size=(5,5))

array([[11, 12, 12, 14, 13],
       [ 9, 10, 11, 11,  8],
       [11,  8, 10,  9, 14],
       [ 7,  8,  9, 15, 15],
       [13,  8,  8,  7,  9]], dtype=int64)

In [38]:
array_RG=gen(pcg(seed=365))
array_RG.binomial(n=100,p=0.5,size=(5,5))

array([[49, 50, 53, 39, 57],
       [45, 54, 44, 50, 47],
       [52, 49, 50, 43, 40],
       [44, 56, 58, 51, 51],
       [56, 43, 54, 55, 55]], dtype=int64)

In [41]:
array_RG=gen(pcg(seed=365))
array_RG.logistic(loc=10,scale=2,size=(5,5))

array([[12.29613037, 12.37419771, 11.05673945,  7.26922378, 11.37144644],
       [ 4.68705208, 11.82257051,  5.77984219, 13.97900427,  9.9524653 ],
       [13.09741163,  9.65135529,  4.93679834, 11.65934468,  8.9089853 ],
       [ 8.28509203,  9.996924  ,  9.89216989, 11.04221783, 10.39751448],
       [11.2288214 ,  3.84844633, 11.89539213, 13.40621303,  6.85131085]])

### Applications of Random Generator

In [43]:
array_RG=gen(pcg(seed=365))
array_column_1=array_RG.normal(loc=10,scale=2,size=(1000))
array_column_2=array_RG.normal(loc=15,scale=3,size=(1000))
array_column_3=array_RG.logistic(loc=10,scale=2,size=(1000))
array_column_4=array_RG.exponential(scale=4,size=(1000))
array_column_5=array_RG.geometric(p=0.5,size=(1000))

In [44]:
random_test_data=np.array([array_column_1,array_column_2,array_column_3,array_column_4,array_column_5])

In [46]:
random_test_data

array([[ 9.72718202, 10.18828862,  9.87399116, ...,  8.79824193,
         7.19322852, 10.60774157],
       [14.13261443, 17.36853483, 12.25905203, ..., 11.01987809,
        16.82646031, 16.35506542],
       [ 9.43132285, 13.28873302,  2.35414141, ...,  4.44323993,
        11.1288541 , 10.53227308],
       [ 6.91500737,  6.243605  ,  2.44997251, ...,  0.80935387,
         0.50644607,  4.86816939],
       [ 2.        ,  1.        ,  1.        , ...,  2.        ,
         3.        ,  1.        ]])

In [47]:
random_test_data.shape

(5, 1000)

In [50]:
random_test_data.transpose
random_test_data

array([[ 9.72718202, 10.18828862,  9.87399116, ...,  8.79824193,
         7.19322852, 10.60774157],
       [14.13261443, 17.36853483, 12.25905203, ..., 11.01987809,
        16.82646031, 16.35506542],
       [ 9.43132285, 13.28873302,  2.35414141, ...,  4.44323993,
        11.1288541 , 10.53227308],
       [ 6.91500737,  6.243605  ,  2.44997251, ...,  0.80935387,
         0.50644607,  4.86816939],
       [ 2.        ,  1.        ,  1.        , ...,  2.        ,
         3.        ,  1.        ]])

In [49]:
random_test_data

array([[ 9.72718202, 10.18828862,  9.87399116, ...,  8.79824193,
         7.19322852, 10.60774157],
       [14.13261443, 17.36853483, 12.25905203, ..., 11.01987809,
        16.82646031, 16.35506542],
       [ 9.43132285, 13.28873302,  2.35414141, ...,  4.44323993,
        11.1288541 , 10.53227308],
       [ 6.91500737,  6.243605  ,  2.44997251, ...,  0.80935387,
         0.50644607,  4.86816939],
       [ 2.        ,  1.        ,  1.        , ...,  2.        ,
         3.        ,  1.        ]])

In [53]:
np.savetxt("RandomTest.csv",random_test_data,fmt="%s",delimiter=',')

In [54]:
np.genfromtxt("RandomTest.csv",delimiter=',')

array([[ 9.72718202, 10.18828862,  9.87399116, ...,  8.79824193,
         7.19322852, 10.60774157],
       [14.13261443, 17.36853483, 12.25905203, ..., 11.01987809,
        16.82646031, 16.35506542],
       [ 9.43132285, 13.28873302,  2.35414141, ...,  4.44323993,
        11.1288541 , 10.53227308],
       [ 6.91500737,  6.243605  ,  2.44997251, ...,  0.80935387,
         0.50644607,  4.86816939],
       [ 2.        ,  1.        ,  1.        , ...,  2.        ,
         3.        ,  1.        ]])