# Array Operations

In [1]:
import numpy as np

## Slicing

In [2]:
matrix_a=np.array([[1,2,3],[4,5,6]])
matrix_a

array([[1, 2, 3],
       [4, 5, 6]])

### Basic Slicing

In [8]:
matrix_a[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
matrix_a[:-1]

array([[1, 2, 3]])

In [11]:
matrix_a[:,:1]

array([[1],
       [4]])

In [13]:
matrix_a[1:,:1]

array([[4]])

### Stepwise Slicing

In [14]:
matrix_B=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
matrix_B

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [18]:
matrix_B[::2,::2]

array([[ 1,  3,  5],
       [11, 13, 15]])

In [19]:
matrix_B[-1::-1,::2]

array([[11, 13, 15],
       [ 6,  8, 10],
       [ 1,  3,  5]])

### Conditional Slicing

In [20]:
matrix_c=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
matrix_c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [22]:
matrix_c[:,0]

array([ 1,  6, 11])

In [23]:
matrix_c[:,0]>2

array([False,  True,  True])

In [24]:
matrix_c[matrix_c[:,:]>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [27]:
matrix_c[(matrix_c[:,:]%2)==0 &(matrix_c[:,:]<=4)]

array([ 2,  4,  6,  8, 10, 12, 14])

## Dimension and the Squeeze Function

In [29]:
matrix_D=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
matrix_D

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [30]:
type(matrix_D[0,0:1])

numpy.ndarray

In [32]:
print(matrix_D[0:1,0:1].squeeze().shape)

()

In [33]:
np.squeeze(matrix_D[0:1,0:1])

array(1)